Nexters/puppycode

lib/pages/home/my_home.dart

- 마이홈 하단 navBar 추가 (바텀시트가 주 목적이라 여긴 좀 대충했어용ㅎ.ㅎ.ㅎ.ㅎ)
- create 버튼 클릭 시 산책 시간 선택하는 바텀시트 레이아웃 구현
- `/home`

기록하기 바텀시트 구현

---

lib/pages/setting/setting.dart
lib/pages/setting/user_info.dart
pubspec.lock
pubspec.yaml

- 알림 시간 설정 
- cupertinoDatePicker 사용
- 알림 on/off 시 시간 설정 enable/disable 설정
todo : dialog 위치 이동..!
- `/settings`

알림 시간 설정 추가

---

lib/pages/friends_list.dart
lib/pages/route.dart
lib/pages/setting/setting.dart
lib/pages/setting/user_info.dart
pubspec.lock
pubspec.yaml

- ... 눌렀을 때 액션 시트 뜨는 것
-  프로필에 뱃지 넣기
- 친구리스트에 아무도 없을 때 레이아웃 (`settings/friendsList`)
- 친구 코드 입력 레이아웃 (`settings/friendsList/code`)
`settings/friendsList`

친구 리스트 페이지 추가

---

lib/pages/home/my_home.dart
lib/src/app.dart

- 디자인이 많이 바뀐 관계로 레이아웃 수정
- AppBar, BotoomBar는 추후 추가

Home 레이아웃 수정

---

lib/pages/feeds/feed_item.dart
lib/pages/feeds/my/myfeed.dart
lib/pages/feeds/my/myfeed_scroll.dart
lib/shared/banner.dart
lib/shared/nav_bar.dart

- column 2의 layout 설정
- 기존 ListView를 GridView로 바꾸는 게 나으려나.. 이건 나중에 시간되면 리팩토링해야겄다 (width, height 설정이 너무 짜침 ㅠ)
- 기존에 구현한 FeedItem 재사용

내 산책일지 레이아웃 구현

---

lib/pages/feedDetails/feed_details.dart
lib/pages/feeds/write.dart
lib/shared/episode.dart
lib/shared/styles/button.dart

에피소드 재사용하게 수정

---

lib/pages/setting/friends_code.dart

- 친구 추가 코드 자동 붙여넣기 기능 넣었슴니다
- 근데 제출 버튼이 없어요
- 디자이너랑 논의하고 완성한 후에 머지하겟슴니당
`/friends/code`

친구 코드 자동 붙여넣기

---

lib/apis/models/friends.dart
lib/pages/feeds/feed_friends.dart
lib/pages/setting/friends_list.dart

- 친구 목록 API 수정된거에 맞춰서 params 값넣었슴댜
- Future도 다 가져올 수 있을 것 같긴 한데, 그래도 반복되는 모델들 빼서 관리하면 괜찮을 것 같아서 api>models에 넣었어용

친구 목록 API 수정

---

lib/apis/models/feed.dart
lib/apis/models/user.dart
lib/config.dart
lib/main.dart
lib/pages/feeds/feed_friends.dart
lib/pages/feeds/feed_item.dart
lib/pages/home/home.dart
lib/pages/setting/user_info.dart
lib/shared/banner.dart
lib/shared/http.dart
lib/shared/image.dart
lib/shared/nav_bar.dart
lib/shared/user.dart

- GetX 활용해서 앱 초기에 userData 가져오게끔
- 페이지에서 userController 가져와서 전역으로 데이터 사용함
- SharedNetworkImage 위젯 클래스 추가 > 로딩, 에러 관리용. 디자인 확인하고 로딩 적용하기
- 그외 자잘한 버그 수정: 시간포맷(한국시간대 변환 등), 오버레이 height 누락돼서 안보이던거 수정

전역 유저 데이터 추가

---

lib/pages/feeds/feed_friends.dart

[TEST_4] 찌르기 기능 구현

---

ios/Runner/Info.plist
lib/pages/feeds/feed_friends.dart
lib/pages/route.dart
lib/pages/setting/friends_list.dart
lib/pages/setting/setting.dart
lib/pages/setting/user_info.dart
lib/shared/image.dart

- 프로필 이미지 유효하지 않은 경우 보여줌
- 테스트 3까지 나왔고 PR 타이틀에 버전 달아서 헷갈리지않게..

[TEST_4] 유저 프로필 이미지 위젯 추가

---

ios/Podfile.lock
ios/Runner/Info.plist
lib/pages/feedDetails/feed_details.dart
lib/pages/setting/user_info.dart
pubspec.lock
pubspec.yaml

- 피드 공유 링크가 저게 맞는지 모르겠서용..
- 공유하기에 AppIcon이 안뜸쓰 .. plist 설정 다 했는데도 안되네용 ㅠㅠ
- share 패키지 넘 구린거라 share-plus로 바꿨어요~ 바꾸면 커스텀이라도 되는 줄 알앗슴.. 없어 그런거 ㅠㅠ
`feed:id`
`settings/userInfo`

[TEST_4] 유저 코드 / 피드 공유

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/main.dart
pubspec.lock
pubspec.yaml

[TEST4] Crashlytics 도입

---

lib/main.dart
pubspec.lock

[TEST6] 파이어베이스 3초 추가

---

lib/apis/models/comment.dart
lib/apis/models/feed.dart
lib/pages/feedDetails/comment_item.dart
lib/pages/feedDetails/feed_details.dart
lib/pages/feedDetails/reaction_contents.dart

[TEST_8] Fix writer label

---

lib/apis/models/push_notification.dart
lib/pages/setting/setting.dart
lib/pages/setting/time_button.dart
lib/shared/http.dart

[TEST_12] 산책알림 

---

lib/pages/feedDetails/comment_item.dart
lib/pages/feedDetails/feed_details.dart
lib/pages/setting/friends_list.dart
lib/pages/setting/user_info.dart
lib/shared/function/sharedAlertDialog.dart

- 유저, 댓글, 피드 신고 기능 추가
- alert 텍스트는 디자이너랑 아직 협의 안된거긴 함..
- 댓글 신고도 아래 스샷이랑 같습니당 ~

신고하기 기능 추가

---

lib/pages/feedDetails/feed_details.dart
lib/pages/feeds/write.dart
lib/shared/episode.dart
lib/shared/nav_bar.dart
lib/shared/photo_item.dart

- 자동 포커싱이랑 UI 수정된 부분 모두 반영했슴니당 ~
- write에 GestureDetector 감싸둔 건 키보드 포커싱 좀 없애고 싶어서.. 추가했어욤 키보드 달린 상태로 스크롤하니까 ux가 너무 별로얌,,
- 그리고 사진 수정은 없으세요 :)
`/write`

피드 수정 포커싱 관련

---

ios/Runner/Info.plist
ios/pawpawWidget/pawpawWidget.swift
lib/pages/calendar/page.dart
lib/pages/feeds/feed_friends.dart
lib/pages/feeds/write.dart
lib/pages/setting/friends_code.dart
lib/shared/styles/button.dart

- 갖가지.. qa.. 더이상.. 못해 ...
- 심사 넣자 ..

[TEST_13] QA

---

ios/Runner/Info.plist
pubspec.lock

- 앨범, 카메라 접근 권한 텍스트 변경
- 빌드 꼬임 이슈 있어서 플러터 업데이트 했습니당

Fix info.plist alert Text
